### ISSUE TITLE
Mikrotik routeros - interface ethernet monitor name once - issue when no link-partner-advertising

### ISSUE THREAD

**Issue by elavaud** [networktocode/ntc-templates#1148]
##### ISSUE TYPE
 - Bug Report

##### TEMPLATE USING
mirkotik routeros interface ethernet monitor {name} once

##### SAMPLE COMMAND OUTPUT
```
                     name: ether30
                    status: no-link
          auto-negotiation: done
               advertising: 10M-half,10M-full,100M-half,100M-full,1000M-half,1000M-full
  link-partner-advertising: 
```

##### SUMMARY
`link-partner-advertising:` is shown in the output although no value is printed
(contrary to other keys of the template, if no value, the corresponding key is not printed)

##### STEPS TO REPRODUCE
Disable an ethernet interface and execute command

##### EXPECTED RESULTS
Empty value

##### ACTUAL RESULTS
```
textfsm.parser.TextFSMError: State Error raised. Rule Line: 21. Input Line:   link-partner-advertising:
```
