### ISSUE TITLE
cisco_nxos_show_interfaces_switchport adds additional space to monitor statement

### ISSUE THREAD

**Issue by Mattias3891** [networktocode/ntc-templates#1317]
Of unknown reason, I get an additional space in the "switchport_monitor" string. 
Thus, having to match "Enabled " and not just Enabled for example.

Example output:
`{'interface': 'Ethernet1/35', 'switchport': 'Enabled', 'switchport_monitor': 'Enabled ', 'mode': 'access', 'access_vlan': '1', 'access_vlan_name': 'default', 'native_vlan': '1', 'native_vlan_name': 'default', 'trunking_vlans': '1-4094', 'voice_vlan': ''}
{'interface': 'Ethernet1/36', 'switchport': 'Enabled', 'switchport_monitor': 'Enabled ', 'mode': 'access', 'access_vlan': '1', 'access_vlan_name': 'default', 'native_vlan': '1', 'native_vlan_name': 'default', 'trunking_vlans': '1-4094', 'voice_vlan': ''}
{'interface': 'port-channel22', 'switchport': 'Enabled', 'switchport_monitor': 'Not enabled ', 'mode': 'trunk', 'access_vlan': '1', 'access_vlan_name': 'default', 'native_vlan': '1', 'native_vlan_name': 'default', 'trunking_vlans': '10-20', 'voice_vlan': ''}
{'interface': 'port-channel23', 'switchport': 'Enabled', 'switchport_monitor': 'Not enabled ', 'mode': 'trunk', 'access_vlan': '1', 'access_vlan_name': 'default', 'native_vlan': '1', 'native_vlan_name': 'default', 'trunking_vlans': '10-20', 'voice_vlan': ''}
{'interface': 'port-channel24', 'switchport': 'Enabled', 'switchport_monitor': 'Not enabled ', 'mode': 'trunk', 'access_vlan': '1', 'access_vlan_name': 'default', 'native_vlan': '1', 'native_vlan_name': 'default', 'trunking_vlans': '10-20', 'voice_vlan': ''}`

To fix this, I've corrected the template to only allow Enabled/Disabled on switchport statement and Enabled/Not enabled on the switchport_monitor statement.

Value Required INTERFACE (\S+)
Value SWITCHPORT (Enabled|Disabled)
Value SWITCHPORT_MONITOR (Enabled|Not\senabled)
Value MODE (access|trunk)

Works well.

**Comment by mjbear** [comment]
Hello @Mattias3891 

I'm a community member volunteering suggestions and possibly to submit a Pull Request (if needed and if you would like).

It's pretty wild how Cisco is adding trailing spaces all of a sudden -- to quite a few things in your example output.

**What version of NXOS are you seeing this with?**


**Conditional Logic Suggestion**
I'm not saying this issue shouldn't be fixed (not my call), but this **_could_** be solved in your :snake: Python code by checking for your desired string in that returned string as opposed to modifying the template.

```
# use the TextFSM structured data instead of this example dictionary
parsed = {'switchport_monitor': 'this string should contain Enabled <space>'}

if 'Enabled' in parsed['switchport_monitor']:
    print('contains Enabled, hooray!')
```


**Reasoning**
If there's anything I've learned from working with regexes and talking to the NTC team, slightly "looser" regexes mean the templates should parse when vendors and situations tweak the output in minor ways.

If `SWITCHPORT` and `MODE` were changed to have specific string values, then if/when there was another value it would not be matched, breaking the template.
https://github.com/networktocode/ntc-templates/blob/master/ntc_templates/templates/cisco_nxos_show_interfaces_switchport.textfsm

**Comment by mjbear** [comment]
@Mattias3891 
Making the regexes for the capture group more rigid is a double edged sword based on experience.

Currently:
`Value SWITCHPORT_MONITOR (.+)`

My suggestion:
`Value SWITCHPORT_MONITOR (\S+(?:\s+\S+)?)`

I'm working up a fix with my suggestion as it meets your needs and should be flexible enough that it will be less likely to break in the future.

```
---
parsed_sample:
  - access_vlan: "1" 
    access_vlan_name: "default"
    interface: "Ethernet1/36"
    mode: "access"
    native_vlan: "1" 
    native_vlan_name: "default"
    switchport: "Enabled"
    switchport_monitor: "Enabled"
    trunking_vlans: "1-4094"
    voice_vlan: ""
  - access_vlan: "1" 
    access_vlan_name: "default"
    interface: "port-channel24"
    mode: "trunk"
    native_vlan: "1" 
    native_vlan_name: "default"
    switchport: "Enabled"
    switchport_monitor: "Not enabled"
    trunking_vlans: "120,134,501,800,804"
    voice_vlan: ""
```
