### ISSUE TITLE
Add cisco_ios_show_wireless_tag_policy_summary

### ISSUE THREAD

**Issue by alexblaeuer** [networktocode/ntc-templates#1826]
### Environment

* ntc-templates version: v6.0.0

### Proposed Functionality

Adding new textfsm template for show wireless tag policy summary Cisco WLC running Cisco IOS XE

### Use Case

Catch the configured Policy Tags on Cisco WLC

##### TEMPLATE USING
```
Value Required POLICY_TAG_NAME (\S+)
Value DESCRIPTION (.+)

Start
  # Skip the header lines
  ^Number of Policy Tags:.*
  ^Policy Tag Name\s+Description
  # Start capturing output
  ^-+ -> PolicyTag
  # Capture time-stamp if vty line has command time-stamping turned on
  ^Load\s+for\s+
  ^Time\s+source\s+is
  # Match blank lines
  ^\s*$$
  # Error out if raw data does not match any above rules.
  ^. -> Error

PolicyTag
  ^${POLICY_TAG_NAME}\s+${DESCRIPTION} -> Record
  # Handle cases where the description is missing
  ^${POLICY_TAG_NAME} -> Record
  # Match blank lines
  ^\s*$$
  # Error out if raw data does not match any above rules.
  ^. -> Error

EOF
```

##### SAMPLE COMMAND OUTPUT
```

Number of Policy Tags: 10

Policy Tag Name                   Description
------------------------------------------------------------------------
PT_VIP                            PT_VIP
PT_Test                           PT_Test
PT_Mgmt
PT_Media                          PT_Media
PT_Default                        PT_Default
PT_Extra
PT_Hallway                        PT_Hallway
default-policy-tag                default policy-tag
```

##### RESULTS

```
---
parsed_sample:
  - description: "PT_VIP"
    policy_tag_name: "PT_VIP"
  - description: "PT_Test"
    policy_tag_name: "PT_Test"
  - description: ""
    policy_tag_name: "PT_Mgmt"
  - description: "PT_Media"
    policy_tag_name: "PT_Media"
  - description: "PT_Default"
    policy_tag_name: "PT_Default"
  - description: ""
    policy_tag_name: "PT_Extra"
  - description: "PT_Hallway"
    policy_tag_name: "PT_Hallway"
  - description: "default policy-tag"
    policy_tag_name: "default-policy-tag"
```
