### ISSUE TITLE
Create cisco_asa_show_running-config_access-group

### ISSUE THREAD

**Issue by wollmannbruno** [networktocode/ntc-templates#1959]
### Environment
* ntc-templates version:  6.0.0

### Proposed Functionality
Create a new template for the `show running-config access-group` command on the Cisco ASA

### Use Case
Ingest the access-list configured on an interface.

#### Proposed Template
```text
Value ACCESS_LIST (\S+)
Value INTERFACE (\S+)


Start
  ^access-group\s+${ACCESS_LIST}\s+in\s+interface\s+${INTERFACE}\s* -> Record
  ^. -> Error "Did not match any entries"

EOF
```

#### Raw Input
```text
# show running-config access-group
access-group INSIDE_acl in interface inside
access-group dmz1_acl in interface dmz1
access-group dmz2_acl in interface dmz2
access-group dmz3_acl in interface dmz3
access-group dmz4 in interface dmz4
access-group dmz5 in interface dmz5
access-group OUTSIDE_acl in interface outside
```

#### Output
```yaml
---
parsed_sample:
  - access_list: "INSIDE_acl"
    interface: "inside"
  - access_list: "dmz1_acl"
    interface: "dmz1"
  - access_list: "dmz2_acl"
    interface: "dmz2"
  - access_list: "dmz3_acl"
    interface: "dmz3"
  - access_list: "dmz4"
    interface: "dmz4"
  - access_list: "dmz5"
    interface: "dmz5"
  - access_list: "OUTSIDE_acl"
    interface: "outside"
```
