### ISSUE TITLE
Create cisco_asa_show_running-config_object_service

### ISSUE THREAD

**Issue by wollmannbruno** [networktocode/ntc-templates#1968]
### Environment
* ntc-templates version:  6.0.0

### Proposed Functionality
Ingest the service objects configured on a Cisco ASA

#### Proposed Template
```
Value Required NAME (\S+)
Value DESCRIPTION (.+)
Value PROTOCOL ([a-z]+)
Value SRC_PORT_EQ (\S+)
Value SRC_PORT_GT (\S+)
Value SRC_PORT_LT (\S+)
Value SRC_PORT_START (\S+)
Value SRC_PORT_END (\S+)
Value DST_PORT_EQ (\S+)
Value DST_PORT_GT (\S+)
Value DST_PORT_LT (\S+)
Value DST_PORT_START (\S+)
Value DST_PORT_END (\S+)

Start
  ^object\s+service -> Continue.Record
  ^object\s+service\s+${NAME}\s*$$
  ^\s+description\s+${DESCRIPTION}\s*$$
  ^\s+service\s+${PROTOCOL}(\s+source\s+(eq\s+${SRC_PORT_EQ}|gt\s+${SRC_PORT_GT}|lt\s+${SRC_PORT_LT}|range\s+${SRC_PORT_START}\s+${SRC_PORT_END}))?(\s+destination\s+(eq\s+${DST_PORT_EQ}|gt\s+${DST_PORT_GT}|lt\s+${DST_PORT_LT}|range\s+${DST_PORT_START}\s+${DST_PORT_END}))?\s*$$
  ^. -> Error "Did not match any lines"
```

#### Raw Input
```
object service one
 description test one
 service tcp source eq 8000 destination eq 9000
object service two
 description test two
 service udp source eq 8000 destination gt 9000
object service three
 description test three
 service tcp source eq 8000 destination lt 9000
object service four
 description test four
 service tcp source eq 8000 destination range 9000 9999
object service five
 description test five
 service tcp source gt 8000 destination eq 9000
object service six
 description test six
 service udp source gt 8000 destination gt 9000
object service seven
 description test seven
 service tcp source gt 8000 destination lt 9000
object service eight
 description test eight
 service tcp source gt 8000 destination range 9000 9999
object service nine
 description test nine
 service tcp source lt 8000 destination eq 9000
object service ten
 description test ten
 service udp source lt 8000 destination gt 9000
object service eleven
 description test eleven
 service tcp source lt 8000 destination lt 9000
object service twelve
 description test twelve
 service tcp source lt 8000 destination range 9000 9999
object service thirteen
 description test twthirteeno
 service tcp source range 8000 8999 destination eq 9000
object service fourteen
 description test fourteen
 service udp source range 8000 8999 destination gt 9000
object service fifteen
 description test fifteen
 service tcp source range 8000 8999 destination lt 9000
object service sixteen
 description test sixteen
 service tcp source range 8000 8999 destination range 9000 9999
object service seventeen
 description test seventeen
 service tcp source eq 8000
object service eighteen
 description test eighteen
 service tcp source gt 8000
object service nineteen
 description test nineteen
 service udp source lt 8000
object service twenty
 description test twenty
 service tcp source range 8000 8999
object service twenty-one
 description test twenty-one
 service tcp destination eq 8000
object service twenty-two
 description test twenty-two
 service tcp destination gt 8000
object service twenty-three
 description test twenty-three
 service tcp destination lt 8000
object service twenty-four
 service udp destination range 8000 8999
```
#### Output
```yaml
---
parsed_sample:
  - description: "test one"
    dst_port_end: ""
    dst_port_eq: "9000"
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: ""
    name: "one"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: "8000"
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: ""
  - description: "test two"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: "9000"
    dst_port_lt: ""
    dst_port_start: ""
    name: "two"
    protocol: "udp"
    src_port_end: ""
    src_port_eq: "8000"
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: ""
  - description: "test three"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: "9000"
    dst_port_start: ""
    name: "three"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: "8000"
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: ""
  - description: "test four"
    dst_port_end: "9999"
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: "9000"
    name: "four"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: "8000"
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: ""
  - description: "test five"
    dst_port_end: ""
    dst_port_eq: "9000"
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: ""
    name: "five"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: "8000"
    src_port_lt: ""
    src_port_start: ""
  - description: "test six"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: "9000"
    dst_port_lt: ""
    dst_port_start: ""
    name: "six"
    protocol: "udp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: "8000"
    src_port_lt: ""
    src_port_start: ""
  - description: "test seven"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: "9000"
    dst_port_start: ""
    name: "seven"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: "8000"
    src_port_lt: ""
    src_port_start: ""
  - description: "test eight"
    dst_port_end: "9999"
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: "9000"
    name: "eight"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: "8000"
    src_port_lt: ""
    src_port_start: ""
  - description: "test nine"
    dst_port_end: ""
    dst_port_eq: "9000"
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: ""
    name: "nine"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: "8000"
    src_port_start: ""
  - description: "test ten"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: "9000"
    dst_port_lt: ""
    dst_port_start: ""
    name: "ten"
    protocol: "udp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: "8000"
    src_port_start: ""
  - description: "test eleven"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: "9000"
    dst_port_start: ""
    name: "eleven"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: "8000"
    src_port_start: ""
  - description: "test twelve"
    dst_port_end: "9999"
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: "9000"
    name: "twelve"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: "8000"
    src_port_start: ""
  - description: "test twthirteeno"
    dst_port_end: ""
    dst_port_eq: "9000"
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: ""
    name: "thirteen"
    protocol: "tcp"
    src_port_end: "8999"
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: "8000"
  - description: "test fourteen"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: "9000"
    dst_port_lt: ""
    dst_port_start: ""
    name: "fourteen"
    protocol: "udp"
    src_port_end: "8999"
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: "8000"
  - description: "test fifteen"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: "9000"
    dst_port_start: ""
    name: "fifteen"
    protocol: "tcp"
    src_port_end: "8999"
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: "8000"
  - description: "test sixteen"
    dst_port_end: "9999"
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: "9000"
    name: "sixteen"
    protocol: "tcp"
    src_port_end: "8999"
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: "8000"
  - description: "test seventeen"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: ""
    name: "seventeen"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: "8000"
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: ""
  - description: "test eighteen"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: ""
    name: "eighteen"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: "8000"
    src_port_lt: ""
    src_port_start: ""
  - description: "test nineteen"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: ""
    name: "nineteen"
    protocol: "udp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: "8000"
    src_port_start: ""
  - description: "test twenty"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: ""
    name: "twenty"
    protocol: "tcp"
    src_port_end: "8999"
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: "8000"
  - description: "test twenty-one"
    dst_port_end: ""
    dst_port_eq: "8000"
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: ""
    name: "twenty-one"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: ""
  - description: "test twenty-two"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: "8000"
    dst_port_lt: ""
    dst_port_start: ""
    name: "twenty-two"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: ""
  - description: "test twenty-three"
    dst_port_end: ""
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: "8000"
    dst_port_start: ""
    name: "twenty-three"
    protocol: "tcp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: ""
  - description: ""
    dst_port_end: "8999"
    dst_port_eq: ""
    dst_port_gt: ""
    dst_port_lt: ""
    dst_port_start: "8000"
    name: "twenty-four"
    protocol: "udp"
    src_port_end: ""
    src_port_eq: ""
    src_port_gt: ""
    src_port_lt: ""
    src_port_start: ""
```
