### ISSUE TITLE
show_lldp_neighbors.template failing when switch + domain name is > 19 characters

### ISSUE THREAD

**Issue by jvanderaa** [networktocode/ntc-templates#375]
##### ISSUE TYPE
 - Bug Report

##### TEMPLATE USING

**cisco_ios_show_lldp_neighbors**
```
Value Required NEIGHBOR (\S+)
Value Required LOCAL_INTERFACE (\S+)
Value Required NEIGHBOR_INTERFACE (\S+)

Start
  ^Device.*ID -> LLDP

LLDP
  ^${NEIGHBOR}\s+${LOCAL_INTERFACE}\s+\d+\s+(\S+)*\s+${NEIGHBOR_INTERFACE} -> Record
  ^${NEIGHBOR}
  ^\s+${LOCAL_INTERFACE}\s+\d+\s+(\S+)*\s+${NEIGHBOR_INTERFACE} -> Record
```

##### SAMPLE COMMAND OUTPUT

```
#show lldp neigh
Capability codes:
    (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
    (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other

Device ID           Local Intf     Hold-time  Capability      Port ID
long_name_swt.josh-vGi0/2          120        R               Gi0/0

Total entries displayed: 1
```

##### SUMMARY

When the hostname + domain name gets long the lldp neighbor output truncates at 20 characters. The result is no record being created and getting a blank completion.

Sample output of NTC Templates with network engine as is:

```
TASK [CLI >> Get LLDP neighbors] *********************************************************************************************************************************************************************************
ok: [rtr01]

TASK [SYS >> Parse LLDP Information] *****************************************************************************************************************************************************************************
ok: [rtr01]

TASK [DEBUG >> LLDP Neighbors] ***********************************************************************************************************************************************************************************
ok: [rtr01] => {
    "msg": []
}

PLAY RECAP *******************************************************************************************************************************************************************************************************
rtr01                      : ok=3    changed=0    unreachable=0    failed=0
```

##### STEPS TO REPRODUCE

```yaml
- name: Switch config
  connection: network_cli
  hosts: cisco_routers
  gather_facts: no
  become: yes
  become_method: enable
  roles:
    - ansible-network.network-engine

  tasks:

    - name: CLI >> Get LLDP neighbors
      ios_command:
        commands:
          - show lldp neighbors
      register: command_output

    - name: SYS >> Parse LLDP Information
      textfsm_parser:
        file: "/opt/ntc-templates/templates/cisco_ios_show_lldp_neighbors.template"
        content: "{{ command_output.stdout[0] }}"
        name: lldp_facts

    - name: DEBUG >> LLDP Neighbors
      debug:
        msg: "{{ ansible_facts.lldp_facts }}"
```

##### EXPECTED RESULTS

I expect to see a neighbor in the output

##### ACTUAL RESULTS

I got a blank facts set as shown above.
