### ISSUE TITLE
New template cisco_ios_show_snmp_user.template

### ISSUE THREAD

**Issue by jifox** [networktocode/ntc-templates#390]
##### ISSUE TYPE

 - Feature Idea

##### TEMPLATE USING

```
Value Required USER_NAME (\w+)
Value ENGINE_ID (\w+)
Value STORAGE_TYPE (\w+)
Value STORAGE_TYPE_ACTIVE (\w+)
Value AUTHENTICATION_PROTOCOL (\w+)
Value PRIVACY_PROTOCOL (\w+)
Value GROUP_NAME (\w+)

Start
  ^User\s+name:\s+${USER_NAME}$$
  ^Engine\s+ID:\s+${ENGINE_ID}$$
  ^storage-type:\s${STORAGE_TYPE}\s+${STORAGE_TYPE_ACTIVE}$$
  ^Authentication\s+Protocol:\s+${AUTHENTICATION_PROTOCOL}$$
  ^Privacy\s+Protocol:\s+${PRIVACY_PROTOCOL}$$
  ^Group-name:\s+${GROUP_NAME}$$ -> Record
```

##### SAMPLE COMMAND OUTPUT

```
TESTSW#show snmp user 

User name: user_snmp1
Engine ID: 80000009030000451DEC1085
storage-type: nonvolatile        active
Authentication Protocol: SHA
Privacy Protocol: AES128
Group-name: managerpriv

User name: user_snmp2
Engine ID: 80000009030000451DEC1085
storage-type: nonvolatile        active
Authentication Protocol: SHA
Privacy Protocol: AES128
Group-name: managerpriv
```

##### STEPS TO REPRODUCE

```yaml
- name: Read snmp users
  ios_command:
    commands:
      - show snmp user
  register: res_snmpuser
  changed_when: false

- set_fact:
    snmp_users: "{{ res_snmpuser.stdout[0] | parse_cli_textfsm(textfsm_template_dir ~ '/cisco_ios_show_snmp_user.template') }}"
  changed_when: false
  delegate_to: localhost

- debug:
    msg: "{{ snmp_users | to_nice_yaml() }}"
  delegate_to: localhost
  changed_when: false
  tags: [print_action]

```

##### ACTUAL RESULTS

```
    -   AUTHENTICATION_PROTOCOL: SHA
        ENGINE_ID: 80000009030000451DEC1085
        GROUP_NAME: managerpriv
        PRIVACY_PROTOCOL: AES128
        STORAGE_TYPE: nonvolatile
        STORAGE_TYPE_ACTIVE: active
        USER_NAME: user_snmp1
    -   AUTHENTICATION_PROTOCOL: SHA
        ENGINE_ID: 80000009030000451DEC1085
        GROUP_NAME: managerpriv
        PRIVACY_PROTOCOL: AES128
        STORAGE_TYPE: nonvolatile
        STORAGE_TYPE_ACTIVE: active
        USER_NAME: user_snmp2

```
