### ISSUE TITLE
cisco_asa bug in 9.10.1.22 causes `show inventory` template to fail

### ISSUE THREAD

**Issue by jvanderaa** [networktocode/ntc-templates#498]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

```
Value NAME (.*)
Value DESCR (.*)
Value PID (\S+)
Value VID (\S+)
Value SN (\S+)

Start
  ^Name:\s+"${NAME}"\s*,\s+DESCR:\s+"${DESCR}"
  ^PID:\s+${PID}\s*,\s+VID:\s+${VID}\s*,\s+SN:\s+${SN} -> Record
  ^\s*$$
  ^.+ -> Error
```

##### SAMPLE COMMAND OUTPUT

```
myfw-fw01# show inv
show_inventory_all -1742439088
Name: "Chassis", DESCR: "ASA 5506-X with FirePOWER services, 8GE, AC, DES"
PID: ASA5506           , VID: V01     , SN: JMX8318372GB

Name: "Storage Device 1", DESCR: "ASA 5506-X SSD"
PID: ASA5506-SSD       , VID: N/A     , SN: MSA1917883N
```

##### SUMMARY

Because of extra output on the command response, the template errors out.

##### STEPS TO REPRODUCE

- Have a device on Cisco ASA 9.10.1.22 code
- Run command `show inventory`
- Send command through a TextFSM parser

```yaml
            - name: "TASK 10: SYS >> Send Serial number to parser"
              textfsm_parser:
                file: "./templates/cisco_asa_show_inventory.template"
                content: "{{ command_output.stdout.0 }}"
                name: inventory_facts
```

##### EXPECTED RESULTS

Same output as that of a non buggy IOS code output

##### ACTUAL RESULTS

- State Error raised

```
FAILED! => {"msg": "State Error raised. Rule Line: 11. Input Line: show_inventory_all -1680491184"}
```

Working on a fix...
