### ISSUE TITLE
show_vlan template for cisco ios does not return more than 60 interfaces

### ISSUE THREAD

**Issue by vinto123** [networktocode/ntc-templates#653]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

cisco_ios_show_vlan.textfsm
```

```
##### SUMMARY

If a cisco 9k (any cisco ios device for that matter) switch has more than 60 ports on it, this parser does not return whole list of ports. I see it is hard-coded to get only first 60 ports.
##### STEPS TO REPRODUCE

pass output of 'show vlan' to this parser and check list of ports in List INTERFACE. 

```yaml

```

##### EXPECTED RESULTS

This parser should return list of all ports from cisco ios device.

**Comment by FragmentedPacket** [comment]
Do you mind providing output with more than 60 ports?

**Comment by vinto123** [comment]
VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Te1/3, Te1/4
2    myvlan                         active      Gi2/2, Gi2/3, Gi2/4, Gi2/5, Gi2/6, Gi2/7, Gi2/8, Gi2/9, Gi2/10, Gi2/11
                                                Gi2/12, Gi2/13, Gi2/14, Gi2/15, Gi2/16, Gi2/17, Gi2/18, Gi2/19, Gi2/20
                                                Gi2/21, Gi2/22, Gi2/23, Gi2/24, Gi2/25, Gi2/26, Gi2/27, Gi2/28, Gi2/29
                                                Gi2/30, Gi2/31, Gi2/32, Gi2/33, Gi2/34, Gi2/35, Gi2/36, Gi2/37, Gi2/38
                                                Gi2/39, Gi2/40, Gi2/41, Gi2/42, Gi2/43, Gi2/44, Gi2/45, Gi2/46, Gi2/47
                                                Gi3/1, Gi3/2, Gi3/3, Gi3/4, Gi3/5, Gi3/6, Gi3/7, Gi3/8, Gi3/9, Gi3/10
                                                Gi3/11, Gi3/12, Gi3/13, Gi3/14, Gi3/15, Gi3/16, Gi3/17, Gi3/18, Gi3/19
                                                Gi3/20, Gi3/21, Gi3/22, Gi3/23, Gi3/24, Gi3/25, Gi3/26, Gi3/27, Gi3/28
                                                Gi3/29, Gi3/30, Gi3/31, Gi3/32, Gi3/33, Gi3/34, Gi3/35, Gi3/36, Gi3/37
                                                Gi3/38, Gi3/39, Gi3/40, Gi3/41, Gi3/42, Gi3/43, Gi3/44, Gi3/45, Gi3/46
                                                Gi3/47, Gi3/48
99   Native                           active

**Comment by vinto123** [comment]
Sorry, i could not make it look like cli output as it is.
Below is screenshot if it helps.
![image](https://user-images.githubusercontent.com/10999410/80007654-6810d980-847b-11ea-8181-49b560b3a5aa.png)

**Comment by FragmentedPacket** [comment]
You can copy and paste out of console and then surround it in triple backticks.

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

I will try and get some work done on this soon :)

**Comment by FragmentedPacket** [comment]
@vinto123 I loaded your data and it appears to capture 94 interfaces.

```yaml
---
parsed_sample:
  - vlan_id: "1"
    name: "default"
    status: "active"
    interfaces:
      - "Te1/3"
      - "Te1/4"
  - vlan_id: "2"
    name: "myvlan"
    status: "active"
    interfaces:
      - "Gi2/2"
      - "Gi2/3"
      - "Gi2/4"
      - "Gi2/5"
      - "Gi2/6"
      - "Gi2/7"
      - "Gi2/8"
      - "Gi2/9"
      - "Gi2/10"
      - "Gi2/11"
      - "Gi2/12"
      - "Gi2/13"
      - "Gi2/14"
      - "Gi2/15"
      - "Gi2/16"
      - "Gi2/17"
      - "Gi2/18"
      - "Gi2/19"
      - "Gi2/20"
      - "Gi2/21"
      - "Gi2/22"
      - "Gi2/23"
      - "Gi2/24"
      - "Gi2/25"
      - "Gi2/26"
      - "Gi2/27"
      - "Gi2/28"
      - "Gi2/29"
      - "Gi2/30"
      - "Gi2/31"
      - "Gi2/32"
      - "Gi2/33"
      - "Gi2/34"
      - "Gi2/35"
      - "Gi2/36"
      - "Gi2/37"
      - "Gi2/38"
      - "Gi2/39"
      - "Gi2/40"
      - "Gi2/41"
      - "Gi2/42"
      - "Gi2/43"
      - "Gi2/44"
      - "Gi2/45"
      - "Gi2/46"
      - "Gi2/47"
      - "Gi3/1"
      - "Gi3/2"
      - "Gi3/3"
      - "Gi3/4"
      - "Gi3/5"
      - "Gi3/6"
      - "Gi3/7"
      - "Gi3/8"
      - "Gi3/9"
      - "Gi3/10"
      - "Gi3/11"
      - "Gi3/12"
      - "Gi3/13"
      - "Gi3/14"
      - "Gi3/15"
      - "Gi3/16"
      - "Gi3/17"
      - "Gi3/18"
      - "Gi3/19"
      - "Gi3/20"
      - "Gi3/21"
      - "Gi3/22"
      - "Gi3/23"
      - "Gi3/24"
      - "Gi3/25"
      - "Gi3/26"
      - "Gi3/27"
      - "Gi3/28"
      - "Gi3/29"
      - "Gi3/30"
      - "Gi3/31"
      - "Gi3/32"
      - "Gi3/33"
      - "Gi3/34"
      - "Gi3/35"
      - "Gi3/36"
      - "Gi3/37"
      - "Gi3/38"
      - "Gi3/39"
      - "Gi3/40"
      - "Gi3/41"
      - "Gi3/42"
      - "Gi3/43"
      - "Gi3/44"
      - "Gi3/45"
      - "Gi3/46"
      - "Gi3/47"
      - "Gi3/48"
  - vlan_id: "99"
    name: "Native"
    status: "active"
    interfaces: []
```

Am I misunderstanding your issue?
