### ISSUE TITLE
cisco_ios_show_ip_access-lists.textfsm is creating an object for the ACL name when it doesn't need to.

### ISSUE THREAD

**Issue by nsnelson402** [networktocode/ntc-templates#956]
##### ISSUE TYPE

 - Bug Report

##### TEMPLATE USING

cisco_ios_show_ip_access-lists.textfsm
```
Value Required,Filldown ACL_TYPE (Standard|Extended)
Value Required,Filldown ACL_NAME (\S+)
Value LINE_NUM (\d+)
Value ACTION (permit|deny)
Value PROTOCOL (\S+)
Value SRC_HOST (\d+\.\d+\.\d+\.\d+)
Value SRC_ANY (any)
Value SRC_NETWORK (\d+\.\d+\.\d+\.\d+)
Value SRC_WILDCARD (\d+\.\d+\.\d+\.\d+)
Value SRC_PORT_MATCH (eq|neq|range|lt|gt)
Value SRC_PORT ((?<!range\s).+?)
Value SRC_PORT_RANGE_START ((?<=range\s)\S+)
Value SRC_PORT_RANGE_END (\S+)
Value DST_HOST (\d+\.\d+\.\d+\.\d+)
Value DST_ANY (any)
Value DST_NETWORK (\d+\.\d+\.\d+\.\d+)
Value DST_WILDCARD (\d+\.\d+\.\d+\.\d+)
Value DST_PORT_MATCH (eq|neq|range|lt|gt)
Value DST_PORT ((?<!range\s).+?)
Value DST_PORT_RANGE_START ((?<=range\s)\S+)
Value DST_PORT_RANGE_END (\S+)
Value FLAGS_MATCH (match-all|match-any)
Value TCP_FLAG (((\+|-|)ack(\s*?)|(\+|-|)established(\s*?)|(\+|-|)fin(\s*?)|(\+|-|)fragments(\s*?)|(\+|-|)psh(\s*?)|(\+|-|)rst(\s*?)|(\+|-|)syn(\s*?)|urg(\s*?))+)
Value LOG (log-input|log)
Value ICMP_TYPE (echo|echo-reply|administratively-prohibited|unreachable|port-unreachable|redirect|router-advertisement|router-solicitation|packet-too-big|time-exceeded|ttl-exceeded|parameter-problem)
Value TIME (\S+)
Value STATE (inactive|active)
Value MATCHES (\d+)

Start
  ^(Standard|Extended) -> Continue.Clearall
  ^${ACL_TYPE}\s+IP\s+access\s+list\s+${ACL_NAME}\s* -> Record
  ^\s+${LINE_NUM}\s+${ACTION}\s+${PROTOCOL}\s+(host\s+${SRC_HOST}|${SRC_ANY}|${SRC_NETWORK}\s+${SRC_WILDCARD})(\s+${SRC_PORT_MATCH}\s+|)(${SRC_PORT_RANGE_START}\s+${SRC_PORT_RANGE_END}|${SRC_PORT}|)\s+(host\s+${DST_HOST}|${DST_ANY}|${DST_NETWORK}\s+${DST_WILDCARD})(\s+${DST_PORT_MATCH}\s+(${DST_PORT_RANGE_START}\s+${DST_PORT_RANGE_END}|${DST_PORT}|)|\s+(${FLAGS_MATCH}\s+|)${TCP_FLAG}|)(\s+${ICMP_TYPE}|)(\s+${LOG}|)(\s+time-range\s+${TIME}\s+\(${STATE}\)|)(?:\s+\(${MATCHES}\s+\S+\)|)\s*$$ -> Record
  ^\s+${LINE_NUM}\s+${ACTION}\s+(${SRC_NETWORK},\s+wildcard\s+bits\s+${SRC_WILDCARD}|${SRC_HOST}|${SRC_ANY})(\s+${LOG}|)(\s+time-range\s+${TIME}\s+\(${STATE}\)|)(?:\s+\(${MATCHES}\s+matches\)|)\s*$$ -> Record
  ^\s*$$
  # Capture time-stamp if vty line has command time-stamping turned on
  ^Load\s+for\s+
  ^Time\s+source\s+is
  ^.* -> Error "Could not parse line:"

EOF

```

##### SAMPLE COMMAND OUTPUT

```
Standard IP access list 99
    10 permit 172.16.191.199
    20 deny   any log
    30 permit 10.0.10.0, wildcard bits 0.255.0.255 (20 matches)
```

##### SUMMARY

The output of the template is returning an object for the ACL name which is not needed, as the ACL name is included in every statement object.

##### STEPS TO REPRODUCE

```yaml
- Execute template against output.
```

##### EXPECTED RESULTS

```
parsed_sample:
  - acl_type: "Standard"
    acl_name: "99"
    line_num: "10"
    action: "permit"
    protocol: ""
    src_host: "172.16.191.199"
    src_any: ""
    src_network: ""
    src_wildcard: ""
    src_port_match: ""
    src_port: ""
    src_port_range_start: ""
    src_port_range_end: ""
    dst_host: ""
    dst_any: ""
    dst_network: ""
    dst_wildcard: ""
    dst_port_match: ""
    dst_port: ""
    dst_port_range_start: ""
    dst_port_range_end: ""
    flags_match: ""
    tcp_flag: ""
    log: ""
    icmp_type: ""
    time: ""
    state: ""
    matches: ""
  - acl_type: "Standard"
    acl_name: "99"
    line_num: "20"
    action: "deny"
    protocol: ""
    src_host: ""
    src_any: "any"
    src_network: ""
    src_wildcard: ""
    src_port_match: ""
    src_port: ""
    src_port_range_start: ""
    src_port_range_end: ""
    dst_host: ""
    dst_any: ""
    dst_network: ""
    dst_wildcard: ""
    dst_port_match: ""
    dst_port: ""
    dst_port_range_start: ""
    dst_port_range_end: ""
    flags_match: ""
    tcp_flag: ""
    log: "log"
    icmp_type: ""
    time: ""
    state: ""
    matches: ""
  - acl_type: "Standard"
    acl_name: "99"
    line_num: "30"
    action: "permit"
    protocol: ""
    src_host: ""
    src_any: ""
    src_network: "10.0.10.0"
    src_wildcard: "0.255.0.255"
    src_port_match: ""
    src_port: ""
    src_port_range_start: ""
    src_port_range_end: ""
    dst_host: ""
    dst_any: ""
    dst_network: ""
    dst_wildcard: ""
    dst_port_match: ""
    dst_port: ""
    dst_port_range_start: ""
    dst_port_range_end: ""
    flags_match: ""
    tcp_flag: ""
    log: ""
    icmp_type: ""
    time: ""
    state: ""
    matches: "20"
```
##### ACTUAL RESULTS

```
parsed_sample:
  - acl_type: "Standard"
    acl_name: "99"
    line_num: ""
    action: ""
    protocol: ""
    src_host: ""
    src_any: ""
    src_network: ""
    src_wildcard: ""
    src_port_match: ""
    src_port: ""
    src_port_range_start: ""
    src_port_range_end: ""
    dst_host: ""
    dst_any: ""
    dst_network: ""
    dst_wildcard: ""
    dst_port_match: ""
    dst_port: ""
    dst_port_range_start: ""
    dst_port_range_end: ""
    flags_match: ""
    tcp_flag: ""
    log: ""
    icmp_type: ""
    time: ""
    state: ""
    matches: ""
  - acl_type: "Standard"
    acl_name: "99"
    line_num: "10"
    action: "permit"
    protocol: ""
    src_host: "172.16.191.199"
    src_any: ""
    src_network: ""
    src_wildcard: ""
    src_port_match: ""
    src_port: ""
    src_port_range_start: ""
    src_port_range_end: ""
    dst_host: ""
    dst_any: ""
    dst_network: ""
    dst_wildcard: ""
    dst_port_match: ""
    dst_port: ""
    dst_port_range_start: ""
    dst_port_range_end: ""
    flags_match: ""
    tcp_flag: ""
    log: ""
    icmp_type: ""
    time: ""
    state: ""
    matches: ""
  - acl_type: "Standard"
    acl_name: "99"
    line_num: "20"
    action: "deny"
    protocol: ""
    src_host: ""
    src_any: "any"
    src_network: ""
    src_wildcard: ""
    src_port_match: ""
    src_port: ""
    src_port_range_start: ""
    src_port_range_end: ""
    dst_host: ""
    dst_any: ""
    dst_network: ""
    dst_wildcard: ""
    dst_port_match: ""
    dst_port: ""
    dst_port_range_start: ""
    dst_port_range_end: ""
    flags_match: ""
    tcp_flag: ""
    log: "log"
    icmp_type: ""
    time: ""
    state: ""
    matches: ""
  - acl_type: "Standard"
    acl_name: "99"
    line_num: "30"
    action: "permit"
    protocol: ""
    src_host: ""
    src_any: ""
    src_network: "10.0.10.0"
    src_wildcard: "0.255.0.255"
    src_port_match: ""
    src_port: ""
    src_port_range_start: ""
    src_port_range_end: ""
    dst_host: ""
    dst_any: ""
    dst_network: ""
    dst_wildcard: ""
    dst_port_match: ""
    dst_port: ""
    dst_port_range_start: ""
    dst_port_range_end: ""
    flags_match: ""
    tcp_flag: ""
    log: ""
    icmp_type: ""
    time: ""
    state: ""
    matches: "20"
```
